trigger:
  branches:
    include:
      - main  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Terraform Cloud API Token (store this in Azure DevOps Pipeline Secrets)
  TF_API_TOKEN: $(TF_API_TOKEN)  # Store securely as a pipeline secret
  # Terraform Cloud Workspace Name
  TF_WORKSPACE: 'aws-ec2-deployment'  # Replace with your Terraform Cloud workspace
  # Terraform Cloud Organization Name
  TF_ORG: 'Terraform_Demo_office'    # Replace with your Terraform Cloud organization
  # AWS Access Credentials (store these in Azure DevOps Pipeline Secrets)
  AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)  # Store securely as a pipeline secret
  AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)  # Store securely as a pipeline secret
  AWS_REGION: 'us-east-1'  # Replace with your AWS region

jobs:
- job: TriggerTerraformCloudRun
  displayName: 'Trigger Terraform Cloud Run'
  steps:
  - task: UseTerraformInstaller@0  # This installs the Terraform CLI
    inputs:
      version: 'latest'  # Install the latest Terraform version

  - script: |
      echo "Triggering Terraform Cloud run..."
      curl -X POST \
        -H "Authorization: Bearer $(TF_API_TOKEN)" \
        -H "Content-Type: application/json" \
        -d '{
              "data": {
                "attributes": {
                  "message": "Triggered from Azure DevOps for EC2 deployment",
                  "is-destroy": false
                },
                "type": "runs",
                "relationships": {
                  "workspace": {
                    "data": {
                      "id": "$(TF_WORKSPACE)",
                      "type": "workspaces"
                    }
                  }
                }
              }
            }' \
        https://app.terraform.io/api/v2/runs
    displayName: 'API Trigger Run for EC2 Instance'

  - script: |
      # Configure AWS CLI with environment variables
      aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
      aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
      aws configure set region $(AWS_REGION)

    displayName: 'Set AWS Credentials'

  - script: |
      echo "Terraform Cloud run triggered and AWS credentials configured."
    displayName: 'Finish Deployment'
